# =============================================================================
# 窗口装饰设置
# =============================================================================
decoration {
    rounding = $ui_window_rounding

    # =========================================================================
    # 模糊效果配置
    # =========================================================================
    blur {
        enabled = $ui_enable_blur
        xray = $ui_blur_xray
        special = $ui_enable_blur_special_ws
        ignore_opacity = true  # 允许透明度模糊
        new_optimizations = true
        popups = $ui_enable_blur_popups
        input_methods = $ui_enable_blur_input_methods
        size = $ui_blur_size
        passes = $ui_blur_passes
    }

    # =========================================================================
    # 阴影效果配置
    # =========================================================================
    shadow {
        enabled = $ui_enable_shadow
        range = $ui_shadow_range
        render_power = $ui_shadow_render_power
        color = $ui_shadow_color
    }
}
