# =============================================================================
# 通用窗口管理器设置
# =============================================================================
general {
    layout = dwindle

    allow_tearing = false  # 允许 `immediate` 窗口规则工作

    gaps_workspaces = $ui_workspace_gaps
    gaps_in = $ui_window_gaps_in
    gaps_out = $ui_window_gaps_out
    border_size = $ui_window_border_size

    col.active_border = $ui_active_border_color
    col.inactive_border = $ui_inactive_border_color
}

# =============================================================================
# Dwindle 布局设置
# =============================================================================
dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = true
}

