# =============================================================================
# 输入设备配置
# =============================================================================
input {
    kb_layout = us
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = $input_enable_touchpad_disable_typing
        scroll_factor = $input_touchpad_scroll_factor
    }
}

# =============================================================================
# 绑定设置
# =============================================================================
binds {
    scroll_event_delay = 0
}

# =============================================================================
# 鼠标指针设置
# =============================================================================
cursor {
    hotspot_padding = 1
}

