# =============================================================================
# 手势配置
# =============================================================================
gestures {
    workspace_swipe_distance = 700
    workspace_swipe_cancel_ratio = 0.15
    workspace_swipe_min_speed_to_force = 5
    workspace_swipe_direction_lock = true
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_create_new = true
}

# =============================================================================
# 手势绑定
# =============================================================================
# 工作区切换手势
gesture = $gesture_workspace_swipe_fingers, horizontal, workspace

# 特殊工作区手势
gesture = $gesture_default_fingers, up, special, special
gesture = $gesture_default_fingers, down, dispatcher, exec, caelestia toggle specialws

# 系统休眠手势
gesture = $gesture_extra_fingers, down, dispatcher, exec, systemctl suspend-then-hibernate
